apiVersion: v1
kind: ServiceAccount
metadata:
  name: emqtt
  labels:
    app.kubernetes.io/name: emqtt
    app.kubernetes.io/part-of: emqtt

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: emqtt
  labels:
    app.kubernetes.io/name: emqtt
    app.kubernetes.io/part-of: emqtt
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: emqtt
  labels:
    app.kubernetes.io/name: emqtt
    app.kubernetes.io/part-of: emqtt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: emqtt
subjects:
  - kind: ServiceAccount
    name: emqtt
    namespace: default
