apiVersion: v1
kind: ServiceAccount
metadata:
  name: emqx
  labels:
    app.kubernetes.io/name: emqx
    app.kubernetes.io/part-of: emqx

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: emqx
  labels:
    app.kubernetes.io/name: emqx
    app.kubernetes.io/part-of: emqx
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: emqx
  labels:
    app.kubernetes.io/name: emqx
    app.kubernetes.io/part-of: emqx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: emqx
subjects:
  - kind: ServiceAccount
    name: emqx
    namespace: default
