apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: emqtt
  labels:
    app.kubernetes.io/name: emqtt
    app.kubernetes.io/part-of: emqtt
data:
  admin_password: dzA4RVF0Qm0xOEtS
  node_cookie: Rmg3T0F3UVVQdzdoZDVJ