apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: emqx
  labels:
    app.kubernetes.io/name: emqx
    app.kubernetes.io/part-of: emqx
data:
  #default emqx password - public
  admin_password: cHVibGlj
  node_cookie: Rmg3T0F3UVVQdzdoZDVJ