apiVersion: v1
kind: Service
metadata:
  name: emqtt-headless
  labels:
    app.kubernetes.io/name: emqtt
    app.kubernetes.io/part-of: emqtt
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: mapping
    port: 4369
    targetPort: mapping
  selector:
    app.kubernetes.io/name: emqtt
    app.kubernetes.io/part-of: emqtt

---

apiVersion: v1
kind: Service
metadata:
  name: emqtt
  labels:
    app.kubernetes.io/name: emqtt
    app.kubernetes.io/part-of: emqtt
spec:
  type: ClusterIP
  ports:
  - name: dashboard
    port: 18083
    targetPort: dashboard
  - name: mgmt
    port: 8080
    targetPort: mgmt
  - name: mqtt
    port: 1883
    targetPort: mqtt
  selector:
    app.kubernetes.io/name: emqtt
    app.kubernetes.io/part-of: emqtt
