apiVersion: v1
kind: Service
metadata:
  name: emqx
  labels:
    app.kubernetes.io/name: emqx
    app.kubernetes.io/part-of: emqx
spec:
  type: ClusterIP
  ports:
  - name: dashboard
    port: 18083
    targetPort: dashboard
  - name: mgmt
    port: 8080
    targetPort: mgmt
  - name: mqtt
    port: 1883
    targetPort: mqtt
  selector:
    app.kubernetes.io/name: emqx
    app.kubernetes.io/part-of: emqx
